Output demo.gif

Set Shell zsh
Set FontFamily "JetBrainsMono Nerd Font"
Set FontSize 28
Set Width 1400
Set Height 1040
Set Theme "GitHub Dark"
Set Padding 20
Set TypingSpeed 50ms

Hide
Type "source ~/.zshenv && source ~/.config/zsh/.zshrc"
Enter
Sleep 2500ms
Ctrl+L
Sleep 500ms
Show

Type "ls"
Sleep 500ms
Enter
Sleep 2500ms

Ctrl+L

Type "head demo.tape"
Sleep 500ms
Enter
Sleep 2500ms

Ctrl+L

Type "gs"
Sleep 500ms
Enter
Sleep 2500ms

Ctrl+L

Type "gl"
Sleep 500ms
Enter
Sleep 2500ms
