# Auto-generated from zsh aliases
# Run: scripts/generate-fish-aliases.sh

alias cat "bat"
alias find "fd"
alias grep "rg"
alias ls "eza --icons=always -a"
alias tree "eza -T -L 4 -a --git-ignore --color=always"
alias cd "z"
alias restow "cd ~/dotfiles && ./scripts/generate-fish-aliases.sh && stow -R ."
alias g "git"
alias ga "git add ."
alias gb "git branch"
alias gc "git commit"
alias gca "git commit --amend"
alias gco "git checkout"
alias gcom "git checkout --ignore-other-worktrees main"
alias gf "git fetch --prune"
alias gl "git log --pretty=format:'%C(yellow)%h%C(reset)%C(red)%d%C(reset)%n%C(cyan)%ar%C(reset) %C(green)<%an>%C(reset)%n%s%n' --no-merges --max-count 5"
alias gp "git pull"
alias gpush "git push"
alias gpo "git pull origin"
alias gpom "git pull origin main"
alias gr "git rebase"
alias grom "git rebase origin/main"
alias gs "git status -s"
alias undo "git reset HEAD~1"
alias wip "git add . && git commit -m 'WIP'"
alias cr "tmux rename-session"
alias commit "claude -p "/commit""
alias claude-update "npm update -g @anthropic-ai/claude-code"
