alias g='git'
alias ga='git add .'
alias gb='git branch'
alias gc='git commit'
alias gca='git commit --amend'
alias gco='git checkout'
alias gcom='git checkout main'
alias gf='git fetch --prune'
alias gl='git log --pretty=format:"%C(yellow)%h%C(reset)%C(red)%d%C(reset)%n%C(cyan)%ar%C(reset) %C(green)<%an>%C(reset)%n%s%n" --no-merges --max-count 5'
alias gp='git pull'
alias gpom='git pull origin main'
alias gr='git rebase'
alias grom='git rebase origin/main'
alias gd='git diff --diff-filter=d; git diff --diff-filter=D --name-status'
alias gdom='git diff --diff-filter=d --stat -p origin/main; git diff --diff-filter=D --name-status origin/main; git ls-files --others --exclude-standard | sed "s/^/??\t/"'
alias gs='git status -s'
alias undo='git reset HEAD~1'
alias wip='git add . && git commit -m WIP'
alias rwt='suffix=$(basename "$(pwd)" | sed "s/.*-//") && git checkout "main-$suffix" && git pull origin main && git fetch --prune'
